name: AST Java Wrapper CI

on: [ pull_request ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Checkout LFS objects
        run: git lfs pull

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
        env:
          CX_CLIENT_ID: ${{ secrets.CX_CLIENT_ID}}
          CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET}}
          CX_BASE_URI: ${{ secrets.CX_BASE_URI }}
          CX_TENANT: ${{ secrets.CX_TENANT }}
          CX_APIKEY: ${{ secrets.CX_APIKEY }}


      - name: Build with Maven
        run: mvn -B verify -DskipTests --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Run SpotBugs Analysis
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
