
name: Checkstyle Linter
on:
  pull_request:
    branches: [ "main" ]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        checkstyle_config: google_checks.xml
        reporter: 'github-pr-check'
        tool_name: 'testtool'
