name: Nightly Release

on:
  push:
    branches:
      - main

jobs:
  delete_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: 0.0.0-SNAPSHOT
  nightly:
    needs: delete_tag
    uses: CheckmarxDev/ast-cli-java-wrapper/.github/workflows/release.yml@main
    with:
      tag: "0.0.0-SNAPSHOT"
      dev: true
      cliTag: "2.0.0-nightly"
    secrets: inherit
