name: Update checkmarx ast cli
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  updateCheckmarxJenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs pull
      - name: Get Latest Checkmarx API version
        id: checkmarx-ast-cli
        run: |
          echo "release_tag=$(curl -sL https://api.github.com/repos/checkmarx/ast-cli/releases/latest | jq -r '.tag_name')" >> $GITHUB_OUTPUT
          echo "current_tag=$(cat checkmarx-ast-cli.version)" >> $GITHUB_OUTPUT
      - name: Update Checkmarx cli version
        if: steps.checkmarx-ast-cli.outputs.current_tag != steps.checkmarx-ast-cli.outputs.release_tag
        env:
          RELEASE_TAG: ${{ steps.checkmarx-ast-cli.outputs.release_tag }}
        run: |
          echo ${{ steps.checkmarx-ast-cli.outputs.release_tag }} > checkmarx-ast-cli.version
      - name: Download latest cli and update branch
        if: steps.checkmarx-ast-cli.outputs.current_tag != steps.checkmarx-ast-cli.outputs.release_tag
        run: |
          chmod +x ./.github/scripts/update_cli.sh
          ./.github/scripts/update_cli.sh ${{ steps.checkmarx-ast-cli.outputs.release_tag }}
      - name: Create Pull Request
        if: steps.checkmarx-ast-cli.outputs.current_tag != steps.checkmarx-ast-cli.outputs.release_tag
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: Update checkmarx-ast-cli to ${{ steps.checkmarx-ast-cli.outputs.release_tag }}
          title: Update checkmarx-ast-cli binaries with ${{ steps.checkmarx-ast-cli.outputs.release_tag }}
          body: |
            Updates [checkmarx-ast-cli][1] to ${{ steps.checkmarx-ast-cli.outputs.release_tag }}
            Auto-generated by [create-pull-request][2]
            [1]: https://github.com/Checkmarx/checkmarx-ast-cli
          labels: cxone
          branch: feature/update_cli