name: Update checkmarx ast cli
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  updateCheckmarxJenkins:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Git LFS
      run: |
        sudo apt-get install git-lfs
        git lfs install

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Get Latest Checkmarx API version
      id: checkmarx-ast-cli
      run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/checkmarx/ast-cli/releases/latest | jq -r ".tag_name")
          echo ::set-output name=current_tag::$(<checkmarx-ast-cli.version)

    - name: Update Checkmarx cli version
      if: steps.checkmarx-ast-cli.outputs.current_tag != steps.checkmarx-ast-cli.outputs.release_tag
      env:
        RELEASE_TAG: ${{ steps.checkmarx-ast-cli.outputs.release_tag }}
      run: |
        # Update current release
        echo ${{ steps.checkmarx-ast-cli.outputs.release_tag }} > checkmarx-ast-cli.version

    - name: Download latest cli and update branch
      if: steps.checkmarx-ast-cli.outputs.current_tag != steps.checkmarx-ast-cli.outputs.release_tag
      run: |
        # Update binaries
        chmod +x ./.github/scripts/update_cli.sh
        ./.github/scripts/update_cli.sh ${{ steps.checkmarx-ast-cli.outputs.release_tag }}

        # Track large files with Git LFS
        git lfs track "src/main/resources/cx-linux"
        git lfs track "src/main/resources/cx.exe"
        git lfs track "src/main/resources/cx-mac"
        git add .gitattributes
        git add src/main/resources/cx-linux src/main/resources/cx.exe src/main/resources/cx-mac

    - name: Create Pull Request
      if: steps.checkmarx-ast-cli.outputs.current_tag != steps.checkmarx-ast-cli.outputs.release_tag
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        commit-message: Update checkmarx-ast-cli to ${{ steps.checkmarx-ast-cli.outputs.release_tag }}
        title: Update checkmarx-ast-cli binaries with ${{ steps.checkmarx-ast-cli.outputs.release_tag }}
        body: |
          Updates [checkmarx-ast-cli][1] to ${{ steps.checkmarx-ast-cli.outputs.release_tag }}

          This update includes large files tracked by Git LFS. Please ensure you have Git LFS installed and initialized before pulling these changes.

          Auto-generated by [create-pull-request][2]
          [1]: https://github.com/Checkmarx/checkmarx-ast-cli
          [2]: https://github.com/peter-evans/create-pull-request
        labels: cxone
        branch: feature/update_cli