name: Update Checkmarx AST CLI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  updateCheckmarxJenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Get Latest Checkmarx API version
        id: checkmarx-ast-cli
        run: |
          latest_tag=$(curl -sL https://api.github.com/repos/checkmarx/ast-cli/releases/latest | jq -r ".tag_name")
          current_tag=$(cat checkmarx-ast-cli.version)
          echo "latest_tag=${latest_tag}" >> $GITHUB_ENV
          echo "current_tag=${current_tag}" >> $GITHUB_ENV

      - name: Update Checkmarx CLI version
        if: env.current_tag != env.latest_tag
        run: |
          echo $latest_tag > checkmarx-ast-cli.version

      - name: Download latest CLI and update branch
        if: env.current_tag != env.latest_tag
        run: |
          chmod +x ./.github/scripts/update_cli.sh
          ./.github/scripts/update_cli.sh ${{ env.latest_tag }}

          # Verify the downloaded CLIs
          for cli in cx.exe cx-linux cx-mac; do
            if [ -f "src/main/resources/$cli" ]; then
              echo "$cli downloaded successfully."
              ls -l src/main/resources/$cli
            else
              echo "$cli download failed."
              exit 1
            fi
          done

          # Track large files with Git LFS
          git lfs track "src/main/resources/cx-linux"
          git lfs track "src/main/resources/cx.exe"
          git lfs track "src/main/resources/cx-mac"
          git add .gitattributes
          git add src/main/resources/cx-linux src/main/resources/cx.exe src/main/resources/cx-mac

      - name: Run Tests
        run: mvn -B test --file pom.xml

      - name: Create Pull Request
        if: env.current_tag != env.latest_tag && success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: Update checkmarx-ast-cli to ${{ env.latest_tag }}
          title: Update checkmarx-ast-cli binaries with ${{ env.latest_tag }}
          body: |
            Updates [checkmarx-ast-cli][1] to ${{ env.latest_tag }}

            This update includes large files tracked by Git LFS. Please ensure you have Git LFS installed and initialized before pulling these changes.

            Auto-generated by [create-pull-request][2]
            [1]: https://github.com/Checkmarx/checkmarx-ast-cli
            [2]: https://github.com/peter-evans/create-pull-request
          labels: cxone
          branch: feature/update_cli